"""TFD Mailbox — a Gmail-styled desktop inbox where interns practice writing
real client emails (reports, proposals, sheets, revisions) against entirely
fictional client addresses (see MAILBOX_CONTACTS). Sending an email schedules
a simulated client auto-response (positive/negative/query/revision-request),
generated by Gemini and delivered by the existing scheduled-tasks cron (see
process_pending_mailbox_responses, hooked into internal_routes.py's
run_scheduled_tasks) rather than a dedicated queue/worker — consistent with
how the AI Manager's daily check-ins are delivered."""

import logging
import random
import uuid
from datetime import datetime, timedelta, timezone

from fastapi import APIRouter, Depends, HTTPException, Query

from database import internship_mailbox_collection, internship_students_collection
from internship_mailbox_models import MailComposeIn, MailContact, MailMessageInDB, MailMessageOut
from internship_models import TRACK_LABELS
from internship_routes import _call_gemini, get_current_student_payload

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/internship", tags=["internship-mailbox"])

MAILBOX_CONTACTS: dict[str, list[dict]] = {
    "finance": [
        {"name": "Rohan Verma", "email": "rohan.verma@client-sim.tfd", "role": "Client — wants monthly P&L / GST / reconciliation reviewed"},
        {"name": "Neha Kapoor", "email": "neha.kapoor@client-sim.tfd", "role": "Client — small business owner, budget/ratio queries"},
    ],
    "marketing": [
        {"name": "Aditya Rao", "email": "aditya.rao@client-sim.tfd", "role": "Client — wants campaign/content plans reviewed"},
        {"name": "Simran Kaur", "email": "simran.kaur@client-sim.tfd", "role": "Client — ad performance / budget queries"},
    ],
    "sales": [
        {"name": "Rajesh Kumar", "email": "rajesh.kumar@client-sim.tfd", "role": "Prospect — evaluating your pipeline/proposal"},
        {"name": "Priyanka Shah", "email": "priyanka.shah@client-sim.tfd", "role": "Prospect — price-sensitive, needs convincing"},
    ],
    "hr": [
        {"name": "Manoj Tiwari", "email": "manoj.tiwari@client-sim.tfd", "role": "Hiring manager — reviewing your shortlist/JDs"},
        {"name": "Divya Iyer", "email": "divya.iyer@client-sim.tfd", "role": "Employee — onboarding/leave/complaint queries"},
    ],
}

_SENTIMENT_WEIGHTS = [("positive", 0.4), ("query", 0.3), ("revision_request", 0.2), ("negative", 0.1)]

_MAIL_REPLY_SYSTEM_PROMPT = """You are {contact_name}, {contact_role}, replying by email to an intern at
The Financial Doctor who just emailed you. Write ONLY the email reply body (no subject line, no
"Dear.../Regards" boilerplate padding beyond a natural greeting/sign-off) — 3-6 sentences, realistic and
businesslike, in the tone of a real {track_label} client/contact. Your reply's sentiment must be: {sentiment}
— positive means genuinely satisfied and appreciative; query means you have a real specific follow-up
question about what they sent; revision_request means you want a specific, named change made before you'll
accept it; negative means you're unhappy about something concrete in what they sent (not just generic
rudeness). React to the actual content of their email below — don't write a generic reply.
Output ONLY the reply text."""


def _student_identity(student: dict) -> dict:
    slug = (student.get("intern_id") or student["id"])[:12].lower()
    return {"name": student.get("name") or "Intern", "email": f"{slug}@intern-sim.tfd"}


def _pick_sentiment(rng: random.Random) -> str:
    r = rng.random()
    cum = 0.0
    for sentiment, weight in _SENTIMENT_WEIGHTS:
        cum += weight
        if r <= cum:
            return sentiment
    return "positive"


async def _to_out(doc: dict) -> MailMessageOut:
    return MailMessageOut(
        id=doc["id"], thread_id=doc["thread_id"], task_id=doc.get("task_id"),
        from_name=doc["from_name"], from_email=doc["from_email"],
        to_name=doc["to_name"], to_email=doc["to_email"],
        subject=doc["subject"], body=doc["body"], direction=doc["direction"],
        status=doc.get("status", "sent"), sentiment=doc.get("sentiment"),
        is_read=doc.get("is_read", False), locked=doc.get("locked", False),
        created_at=doc["created_at"],
    )


@router.get("/mailbox/contacts", response_model=list[MailContact])
async def get_mailbox_contacts(payload: dict = Depends(get_current_student_payload)):
    student = await internship_students_collection.find_one({"id": payload["sub"]})
    if not student or not student.get("track"):
        raise HTTPException(status_code=400, detail="Please select a track first")
    return [MailContact(**c) for c in MAILBOX_CONTACTS.get(student["track"], [])]


@router.get("/mailbox/messages", response_model=list[MailMessageOut])
async def list_mailbox_messages(folder: str = Query(default="inbox"), payload: dict = Depends(get_current_student_payload)):
    if folder not in ("inbox", "sent", "drafts"):
        raise HTTPException(status_code=400, detail="Invalid folder")
    query = {"student_id": payload["sub"]}
    if folder == "inbox":
        query["direction"] = "inbound"
    elif folder == "sent":
        query["direction"] = "outbound"
        query["status"] = "sent"
    else:
        query["direction"] = "outbound"
        query["status"] = "draft"
    docs = [d async for d in internship_mailbox_collection.find(query).sort("created_at", -1)]
    return [await _to_out(d) for d in docs]


@router.get("/mailbox/thread/{thread_id}", response_model=list[MailMessageOut])
async def get_mailbox_thread(thread_id: str, payload: dict = Depends(get_current_student_payload)):
    docs = [d async for d in internship_mailbox_collection.find(
        {"student_id": payload["sub"], "thread_id": thread_id}
    ).sort("created_at", 1)]
    if not docs:
        raise HTTPException(status_code=404, detail="Thread not found")
    await internship_mailbox_collection.update_many(
        {"student_id": payload["sub"], "thread_id": thread_id, "direction": "inbound"},
        {"$set": {"is_read": True}},
    )
    return [await _to_out(d) for d in docs]


@router.get("/mailbox/unread-count")
async def mailbox_unread_count(payload: dict = Depends(get_current_student_payload)):
    count = await internship_mailbox_collection.count_documents(
        {"student_id": payload["sub"], "direction": "inbound", "is_read": False}
    )
    return {"unread": count}


@router.post("/mailbox/compose", response_model=MailMessageOut)
async def compose_mail(data: MailComposeIn, payload: dict = Depends(get_current_student_payload)):
    student = await internship_students_collection.find_one({"id": payload["sub"]})
    if not student or not student.get("track"):
        raise HTTPException(status_code=400, detail="Please select a track first")

    contacts = {c["email"]: c for c in MAILBOX_CONTACTS.get(student["track"], [])}
    contact = contacts.get(data.to_email)
    if not contact:
        raise HTTPException(status_code=400, detail="Unknown recipient for your track")

    thread_id = data.thread_id or str(uuid.uuid4())
    if data.thread_id:
        existing = await internship_mailbox_collection.find_one({"student_id": student["id"], "thread_id": thread_id})
        if existing and existing.get("locked"):
            raise HTTPException(status_code=409, detail="This thread is locked — the task it belongs to has already been graded")

    identity = _student_identity(student)
    now = datetime.now(timezone.utc)
    status = "draft" if data.is_draft else "sent"
    doc = MailMessageInDB(
        student_id=student["id"], thread_id=thread_id, task_id=data.task_id,
        from_name=identity["name"], from_email=identity["email"],
        to_name=contact["name"], to_email=contact["email"],
        subject=data.subject, body=data.body, direction="outbound", status=status,
        response_due_at=(now + timedelta(minutes=random.randint(20, 240))) if status == "sent" else None,
    ).dict()
    await internship_mailbox_collection.insert_one(doc)
    return await _to_out(doc)


@router.post("/mailbox/draft/{message_id}/send", response_model=MailMessageOut)
async def send_draft(message_id: str, payload: dict = Depends(get_current_student_payload)):
    doc = await internship_mailbox_collection.find_one({"id": message_id, "student_id": payload["sub"], "status": "draft"})
    if not doc:
        raise HTTPException(status_code=404, detail="Draft not found")
    now = datetime.now(timezone.utc)
    await internship_mailbox_collection.update_one(
        {"id": message_id},
        {"$set": {"status": "sent", "created_at": now, "response_due_at": now + timedelta(minutes=random.randint(20, 240))}},
    )
    doc = await internship_mailbox_collection.find_one({"id": message_id})
    return await _to_out(doc)


async def _generate_client_reply(student: dict, contact: dict, outbound: dict, sentiment: str) -> str:
    prompt_input = f"Their email —\nSubject: {outbound['subject']}\n\n{outbound['body']}"
    system = _MAIL_REPLY_SYSTEM_PROMPT.format(
        contact_name=contact["name"], contact_role=contact["role"],
        track_label=TRACK_LABELS.get(student.get("track"), student.get("track")), sentiment=sentiment,
    )
    text_out = await _call_gemini(system, prompt_input, temperature=0.6)
    if text_out:
        return text_out.strip()
    fallback = {
        "positive": "Thanks for sending this over — looks good on my end, appreciate the quick turnaround!",
        "query": "Thanks for this — quick question though, can you clarify one of the numbers/points before I sign off?",
        "revision_request": "Thanks for sending this, but I need one change made before I can accept it — can you revise and resend?",
        "negative": "I went through this and I'm not happy with a couple of things here — can we get on this again properly?",
    }
    return fallback.get(sentiment, fallback["query"])


async def process_pending_mailbox_responses() -> dict:
    """Cron entrypoint (see internal_routes.py's run_scheduled_tasks) — finds
    sent outbound mails whose simulated response window has elapsed and no
    reply exists yet, generates the client's reply via Gemini, inserts it as
    an inbound message in the same thread, and notifies the student."""
    sent = 0
    errors = 0
    now = datetime.now(timezone.utc)
    async for outbound in internship_mailbox_collection.find({
        "direction": "outbound", "status": "sent", "response_generated": {"$ne": True},
        "response_due_at": {"$lte": now},
    }):
        try:
            student = await internship_students_collection.find_one({"id": outbound["student_id"]})
            if not student:
                continue
            contact = next((c for c in MAILBOX_CONTACTS.get(student.get("track"), []) if c["email"] == outbound["to_email"]), None)
            if not contact:
                continue
            rng = random.Random(f"mailbox:{outbound['id']}")
            sentiment = _pick_sentiment(rng)
            reply_body = await _generate_client_reply(student, contact, outbound, sentiment)
            reply_doc = MailMessageInDB(
                student_id=student["id"], thread_id=outbound["thread_id"], task_id=outbound.get("task_id"),
                from_name=contact["name"], from_email=contact["email"],
                to_name=outbound["from_name"], to_email=outbound["from_email"],
                subject=f"Re: {outbound['subject']}", body=reply_body,
                direction="inbound", status="sent", sentiment=sentiment,
            ).dict()
            await internship_mailbox_collection.insert_one(reply_doc)
            await internship_mailbox_collection.update_one({"id": outbound["id"]}, {"$set": {"response_generated": True}})

            try:
                from notification_service import create_notification
                await create_notification(
                    user_id=student["id"], title=f"New reply from {contact['name']}",
                    body=reply_body[:120], n_type="internship_mailbox", link="/portal/student/mailbox",
                )
            except Exception:
                logger.warning("Failed to notify student %s of mailbox reply", student["id"])
            sent += 1
        except Exception:
            errors += 1
    return {"sent": sent, "errors": errors}
