"""Notification helpers: store in-app notifications and send via raw Web Push (VAPID).

One delivery mechanism for every platform — desktop Chrome/Edge, Android Chrome,
and iOS Safari (installed as a Home Screen PWA, iOS 16.4+). Deliberately not
Firebase Cloud Messaging: FCM's iOS delivery path requires an Apple Push
Notification (APNs) Auth Key, which can only be generated by enrolling in the
paid Apple Developer Program. The standard W3C Push API used here is natively
implemented by WebKit on iOS for installed PWAs with no Apple account needed.
"""
import os
import json
import logging

from notification_models import NotificationInDB
from database import notifications_collection, push_subscriptions_collection

logger = logging.getLogger(__name__)

VAPID_PUBLIC_KEY = os.environ.get("VAPID_PUBLIC_KEY", "")
VAPID_PRIVATE_KEY = os.environ.get("VAPID_PRIVATE_KEY", "")
VAPID_CLAIM_EMAIL = os.environ.get("VAPID_CLAIM_EMAIL", "mailto:admin@thefinancialdoctor.in")

try:
    from pywebpush import webpush, WebPushException
    _PUSH_AVAILABLE = True
except Exception:
    _PUSH_AVAILABLE = False


def push_enabled() -> bool:
    return bool(_PUSH_AVAILABLE and VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY)


async def _send_web_push(user_id: str, payload: dict) -> None:
    if not push_enabled():
        return
    cursor = push_subscriptions_collection.find({"user_id": user_id})
    async for sub in cursor:
        try:
            webpush(
                subscription_info={"endpoint": sub["endpoint"], "keys": sub["keys"]},
                data=json.dumps(payload),
                vapid_private_key=VAPID_PRIVATE_KEY,
                vapid_claims={"sub": VAPID_CLAIM_EMAIL},
            )
        except WebPushException as exc:
            logger.warning("Web push failed for %s: %s", user_id, exc)
            # 404/410 = subscription gone; 401/403 = VAPID key mismatch (the
            # subscription was created against a different server key, e.g.
            # before a key rotation) — both cases mean this subscription can
            # never succeed again and must be re-created client-side, so prune
            # it rather than retrying it forever.
            if getattr(exc, "response", None) is not None and exc.response.status_code in (401, 403, 404, 410):
                await push_subscriptions_collection.delete_one({"_id": sub["_id"]})
        except Exception as exc:
            logger.warning("Web push error for %s: %s", user_id, exc)


async def create_notification(
    user_id: str,
    title: str,
    body: str,
    n_type: str = "general",
    link: str | None = None,
) -> None:
    """Store an in-app notification and send it via VAPID web push."""
    note = NotificationInDB(user_id=user_id, title=title, body=body, type=n_type, link=link)
    await notifications_collection.insert_one(note.dict())
    # "url" matches the key public/web-push-sw.js reads (shared by portal + website).
    await _send_web_push(
        user_id,
        {"title": title, "body": body, "url": link or "/portal/employee"},
    )
