/**
 * Generates public/firebase-messaging-sw.js from the same REACT_APP_FIREBASE_*
 * env vars used by src/firebaseConfig.js.
 *
 * Service workers are static files served as-is by CRA — they never go through
 * webpack/babel, so `process.env.REACT_APP_*` substitution does NOT apply to
 * anything under public/. Without this script the file has to be hand-edited
 * every time the Firebase project config changes, which is how it was left
 * checked in with literal "PLACEHOLDER" values (breaking all background/OS
 * push notifications — the SW's firebase.initializeApp() couldn't talk to the
 * real project). Runs automatically before `start`/`build` so the SW config
 * always matches whatever is in .env.
 */
const fs = require("fs");
const path = require("path");
require("dotenv").config();

const cfg = {
  apiKey: process.env.REACT_APP_FIREBASE_API_KEY || "",
  authDomain: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN || "",
  projectId: process.env.REACT_APP_FIREBASE_PROJECT_ID || "",
  storageBucket: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET || "",
  messagingSenderId: process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID || "",
  appId: process.env.REACT_APP_FIREBASE_APP_ID || "",
};

const missing = Object.entries(cfg).filter(([, v]) => !v).map(([k]) => k);
if (missing.length) {
  console.warn(
    `[generate-fcm-sw] Missing Firebase env vars: ${missing.join(", ")}. ` +
    "Background push notifications will not work until these are set in frontend/.env " +
    "(same REACT_APP_FIREBASE_* keys used in src/firebaseConfig.js)."
  );
}

const sw = `/* AUTO-GENERATED by scripts/generate-fcm-sw.js — do not edit by hand.
 * Regenerated from frontend/.env on every \`yarn start\` / \`yarn build\`. */
/* eslint-disable no-restricted-globals */
importScripts("https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/10.12.0/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(cfg, null, 2)});

const messaging = firebase.messaging();

// Sent as a data-only FCM payload (see backend/notification_service.py) so this
// handler always runs — a "notification" payload would instead be auto-displayed
// by the browser itself, bypassing our icon/logo and click routing entirely.
messaging.onBackgroundMessage((payload) => {
  const { title, body, link } = payload.data || payload.notification || {};
  self.registration.showNotification(title || "TFD Workspace", {
    body: body || "",
    icon: "/tfd-workspace-logo.png",
    badge: "/tfd-workspace-logo.png",
    data: { url: link || "/portal/employee" },
  });
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const url = event.notification.data && event.notification.data.url || "/portal/employee";
  event.waitUntil(clients.openWindow(url));
});
`;

const outPath = path.resolve(__dirname, "..", "public", "firebase-messaging-sw.js");
fs.writeFileSync(outPath, sw);
console.log(`[generate-fcm-sw] Wrote ${outPath}`);
